### ISSUE TITLE
关于预处理过程引入干扰信息的讨论

### ISSUE THREAD

**Issue by Apollo0801** [wmn7/Traffic-Classification#8]
https://github.com/wmn7/Traffic-Classification/blob/8a9271216072a3e2d8d3058d98397361f55c394d/TrafficFlowClassification/preprocess/pcap2npy.py#L14

直接利用二进制方式读取，会引入.pcap格式文件的文件头信息。文件头信息与流量行为本身无关，但可能与数据采集行为有关，故应为干扰信息。

**Comment by wmn7** [comment]
你好，

因为我现在不再继续做这个方向了，代码可能不再更新，不过非常欢迎你接着这个代码进行修改，有具体问题也可以简单讨论一下（不过很多细节我可能不太记得了）。

现在我主要工作重点在智慧城市仿真方面，https://github.com/Traffic-Alpha。


祝好，
王茂南

**Comment by Apollo0801** [comment]
收到

**Comment by Apollo0801** [comment]
> 你好，
> 
> 因为我现在不再继续做这个方向了，代码可能不再更新，不过非常欢迎你接着这个代码进行修改，有具体问题也可以简单讨论一下（不过很多细节我可能不太记得了）。
> 
> 现在我主要工作重点在智慧城市仿真方面，[https://github.com/Traffic-Alpha。](https://github.com/Traffic-Alpha%E3%80%82)
> 
> 祝好， 王茂南

收到，谢谢回复！
